### ISSUE TITLE
[Request] Add support for mega to gdrive upload

### ISSUE THREAD

**Issue by askfriends** [MaxxRider/Leech-Pro#19]
Add support for mega to gdrive upload. its available in some other repos. hope u can do it too.

**Comment by MaxxRider** [comment]
can you mention that repo 🤔
which is support mega

**Comment by askfriends** [comment]
> can you mention that repo 🤔
> which is support mega

one of them is https://github.com/priiiiyo/priiiiyo-mirror-bot

**Comment by MaxxRider** [comment]
This is a Leech Repo

and you send me Mirror Repo 🙄🙄

best Mirror repo

https://github.com/breakdowns/slam-mirrorbot

Deploy this 

mega is limited 2GB  ( non premium users)

**Comment by askfriends** [comment]
> This is a Leech Repo
> 
> and you send me Mirror Repo 🙄🙄
> 
> best Mirror repo
> 
> https://github.com/breakdowns/slam-mirrorbot
> 
> Deploy this
> 
> mega is limited 2GB ( non premium users)

you mean i can only mirror mega links from my mega account only?
