### ISSUE TITLE
Kangers Should Be Ashamed

### ISSUE THREAD

**Issue by AmirulAndalib** [MaxxRider/Leech-Pro#30]
https://github.com/MaxxRider/Leech-Pro/commit/da538a7d432df2472b4339eb237fe1247340aef5

**Comment by AmirulAndalib** [comment]
## https://github.com/MaxxRider/Leech-Pro/commit/da538a7d432df2472b4339eb237fe1247340aef5

**Comment by AmirulAndalib** [comment]
# all copied from https://github.com/XcodersHub/TorrentLeechx

**Comment by adityasirohi4** [comment]
Yes you have all copy our friend pero coder repo you should be ashamed

**Comment by SuggalaVamsi** [comment]
> [da538a7](https://github.com/MaxxRider/Leech-Pro/commit/da538a7d432df2472b4339eb237fe1247340aef5)
> 
> ## you guys Should Be Ashamed for Copying my repo And Besides i can report it to github and take down This Repo With Proofs If i submit

**Comment by adityasirohi4** [comment]
**ʏᴏᴜ ɢᴜʏꜱ ꜱʜᴏᴜʟᴅ ʙᴇ ᴀꜱʜᴀᴍᴇᴅ ꜰᴏʀ ᴄᴏᴘʏɪɴɢ ᴍʏ ʀᴇᴘᴏ ᴀɴᴅ ʙᴇꜱɪᴅᴇꜱ ɪ ᴄᴀɴ ʀᴇᴘᴏʀᴛ ɪᴛ ᴛᴏ ɢɪᴛʜᴜʙ ᴀɴᴅ ᴛᴀᴋᴇ ᴅᴏᴡɴ ᴛʜɪꜱ ʀᴇᴘᴏ ᴡɪᴛʜ ᴘʀᴏᴏꜰꜱ ɪꜰ ɪ ꜱᴜʙᴍɪt**

**Comment by adityasirohi4** [comment]
### ʏᴏᴜ ɢᴜʏꜱ ꜱʜᴏᴜʟᴅ ʙᴇ ᴀꜱʜᴀᴍᴇᴅ ꜰᴏʀ ᴄᴏᴘʏɪɴɢ ᴍʏ ʀᴇᴘᴏ ᴀɴᴅ ʙᴇꜱɪᴅᴇꜱ ɪ ᴄᴀɴ ʀᴇᴘᴏʀᴛ ɪᴛ ᴛᴏ ɢɪᴛʜᴜʙ ᴀɴᴅ ᴛᴀᴋᴇ ᴅᴏᴡɴ ᴛʜɪꜱ ʀᴇᴘᴏ ᴡɪᴛʜ ᴘʀᴏᴏꜰꜱ ɪꜰ ɪ ꜱᴜʙᴍɪt

**Comment by adityasirohi4** [comment]
## Yes you have all copy our friend pero coder repo you should be ashamed

**Comment by shadowhunter777** [comment]
## Yes you have all copy our friend pero coder repo you should be ashamed..learn to give credits mr noob

**Comment by leaderJR** [comment]
## Yes you have all copy our friend pero coder repo you should be ashamed...U can't do anything on your own🤣 bcoz u are a loser

**Comment by mr-antisecurity** [comment]
## Yes you  all copied our friend pero coder repo. You should be ashamed for that guys!

**Comment by AmirulAndalib** [comment]
# 😌
