### ISSUE TITLE
Error in the logs

### ISSUE THREAD

**Issue by Luqsonic** [MaxxRider/Leech-Pro#34]
It brings error in the logs...how do i fix that? See attached photo

![SmartSelect_20210923-175344_Via](https://user-images.githubusercontent.com/62737177/134530993-ddd7829e-6bbf-4dc8-a832-6627564fe07a.jpg)

**Comment by MaxxRider** [comment]
Bot working or not?

**Comment by Luqsonic** [comment]
> Bot working or not?

No it's not working

**Comment by H1kikomoR1** [comment]
that not error

**Comment by MaxxRider** [comment]
Turn off Dyno and check again

**Comment by svacva** [comment]
same error
